---
- name: install cassandra repository
  yum_repository:
    name: cassandra
    description: Apache Cassandra
    baseurl: "{{ cassandra_repo }}"
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://downloads.apache.org/cassandra/KEYS

- name: install cassandra packages
  package:
    name: "{{ cassandra_package_names }}"
    state: "{{ cassandra_package_state }}"

- block:

    - name: install jolokia jar
      get_url:
        url: "{{ cassandra_jolokia_agent_url }}"
        dest: "{{ cassandra_jolokia_agent_path }}"

    - name: configure jolokia agent
      lineinfile:
        path: "{{ cassandra_defaults_file }}"
        regexp: "^JVM_OPTS="
        line: "JVM_OPTS=\"$JVM_OPTS -javaagent:{{ cassandra_jolokia_agent_path }},port={{ cassandra_jolokia_port }},host={{ cassandra_jolokia_host }}\""
      notify: restart cassandra

  when: cassandra_jolokia_manage | bool
