---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        cassandra_nolog: no
        cassandra_role_pass: cassandra
        cassandra_roles:
          - name: topsecret
            password: topsecret
            superuser: true
          - name: nosecret
            password: nosecret
            superuser: false
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - side_effect
    - converge
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
