---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: instance1
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
  - name: instance2
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
  - name: instance3
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        cassandra_role_pass: topsecret
        cassandra_hosts: "{{ groups['all'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"
verifier:
  name: testinfra
